### ISSUE TITLE
vendor/vkd3d: Makefile fails at configure step

### ISSUE THREAD

**Issue by mozo78** [kakra/wine-proton#1]
Hello,
It seems that I can't understand how to issue git rebase -i winehq/master. It always give me an error. Here are the steps that I follow:
1. git remote add winehq git://source.winehq.org/git/wine.git
2. cd wine-proton
3. git remote update
4. git submodule update --init
5. git rebase -i winehq/master
And when I try "git rebase -i winehq/master" it gives me:
`fatal: invalid upstream 'winehq/master'`

Despite of this problem I tried to build but again without success. It gives me the following error:
https://pastebin.com/RugWBbsh

**Comment by kakra** [comment]
Just omit step 5... You don't need to rebase unless you know why. I uploaded a pre-compiled version to the releases page here: https://github.com/kakra/wine-proton/releases

Otherwise, you need to add the winehq upstream project within the project:

```bash
cd wine-proton
git remote add winehq git://source.winehq.org/git/wine.git
git remote update
```

Now git will know `winehq/master`.

**Comment by kakra** [comment]
This particular error was fixed:

```
make -C vendor/vkd3d configure
make[2]: Entering directory '/home/mozo/Downloads/wine-proton/vendor/vkd3d'
mkdir -p build/wine32
cd build/wine32/ && ../../configure --host="i686-pc-linux-gnu" --prefix=/ --with-spirv-tools --libdir=/lib LDFLAGS="-m32" CFLAGS="-m32 -O2 -march=native -fomit-frame-pointer -g0 -fipa-pta -I/home/mozo/Downloads/wine-proton/vendor/vulkan-headers/include" PKG_CONFIG_PATH=/usr/lib32/pkgconfig
/bin/sh: ../../configure: No such file or directory
make[2]: *** [makefile:22: build/wine32/Makefile] Error 127
make[2]: Leaving directory '/home/mozo/Downloads/wine-proton/vendor/vkd3d'
make[1]: *** [makefile:80: configure-vkd3d] Error 2
make[1]: Leaving directory '/home/mozo/Downloads/wine-proton'
make: *** [makefile:95: configure] Error 2
```

Just run

```bash
git remote update
git reset --hard
git submodule update --force
```

**Comment by kakra** [comment]
Please re-open if you're still having issues with this. Open a new issue for a different problem. Thanks. :-)

**Comment by mozo78** [comment]
Thank you. Now "git rebase -i winehq/master" works but I still can't compile. This time the error is:
https://pastebin.com/pHBjhuzw

**Comment by kakra** [comment]
I suppose you still missed to

```bash
git submodule update --init
```

Maybe start from scratch. Remove the directory and follow the [README.md](https://github.com/kakra/wine-proton/blob/rebase/proton_3.16/README.md#cloning-the-repository-and-setup).

**Comment by mozo78** [comment]
I already started from scratch:

https://pastebin.com/0zzRv0La

**Comment by kakra** [comment]
This is strange, give me some time to reproduce this from a clean environment. What distribution are you using?

**Comment by kakra** [comment]
Just a quick note, please try

```bash
# Run some preparation scripts first:
pushd vendor/vkd3d && ./autogen.sh && popd
```

before the first `make` step and let me know if that fixes things. If yes, I guess my documentation is incomplete. ;-)

**Comment by mozo78** [comment]
Unfortunately it doesn't help:
https://pastebin.com/V6tTRvkN
I'm on Arch Linux.

**Comment by kakra** [comment]
Actually, it helped. We are now seeing a completely different issue. You need spirv-headers and spirv-tools, probably others, too. Would you mind opening a new issue for this, mentioning Arch? Thanks.

**Comment by kakra** [comment]
This is fixed now by updating the `README.md`. Next push will contain the fix.
